version: "3.7"

services:
  postgresdb:
    image: postgres:14
    container_name: PIU_VanatoareaDeDiamante
    restart: always
    command:
      -p 5433
    environment:
      POSTGRES_DB: piu_project
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5433